/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 garage.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model_garage(props) {
  const { nodes, materials } = useGLTF('/garage.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Node1.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node2.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node3.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node4.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node5.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node6.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node7.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node8.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node9.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node10.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node11.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node12.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node13.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node14.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node15.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node16.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node17.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node18.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node19.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node20.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node21.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node22.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node23.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node24.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node25.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node26.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node27.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node28.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node29.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node30.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node31.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node32.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node33.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node34.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node35.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node36.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node37.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node38.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node39.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node40.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node41.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node42.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node43.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node44.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node45.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node46.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node47.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node48.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node49.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node50.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node51.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node52.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node53.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node54.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node55.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node56.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node57.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node58.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node59.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node60.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node61.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node62.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node63.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node64.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node65.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node66.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node67.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node68.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node69.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node70.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node71.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node72.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node73.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node74.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node75.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node76.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node77.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node78.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node79.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node80.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node81.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node82.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node83.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node84.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node85.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node86.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node87.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node88.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node89.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node90.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node91.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node92.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node93.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node94.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node95.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node96.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node97.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node98.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node99.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node100.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node101.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node102.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node103.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node104.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node105.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node106.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node107.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node108.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node109.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node110.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node111.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node112.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node113.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node114.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node115.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node116.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node117.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node118.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node119.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node120.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node121.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node122.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node123.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node124.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node125.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node126.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node127.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node128.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node129.geometry} material={materials.x1} />
      <mesh geometry={nodes.Node130.geometry} material={materials.x1} />
    </group>
  )
}

useGLTF.preload('/garage.gltf')
